### ISSUE TITLE
.rbenv-vars, passenger, not working

### ISSUE THREAD

**Issue by sdarwin** [rbenv/rbenv-vars#27]
Hi, this might turn out to be a spurious bug report, but I will quickly post it.  With a global rbenv installation in /opt/rbenv , and the latest ruby on rails, the .rbenv-vars variables are appearing perfectly on the bash command-line, and in ruby scripts, however not on the website, observing those ENV variables all the newly assigned env vars are missing, as far as "RBENV" only "RBENV_ROOT"=>"/opt/rbenv" and "RBENV_SHELL"=>"bash" are set, no others. Have tried placing .rbenv-vars in many dir locations. Any ideas? Thanks.

**Comment by mislav** [comment]
Sorry you're having trouble, but I'm not sure I understand what are you reporting.

If you have `.rbenv-vars` file with the contents `FOO=bar` in your project's root directory, whenever you run a ruby script in that directory the `ENV["FOO"]` should have a value. Are you saying that works locally, but not in production?

How is Passenger configured? Does it spin up Ruby processes directly, or through rbenv? Chances are that it does it directly, which gives no opportunity to rbenv or rbenv-vars to step in and load these variables.

One solution might be to copy `.rbenv-vars` to `.env` file in production and [add `dotenv-rails` gem](https://github.com/bkeepers/dotenv#readme) to your project's bundle. Then you don't need rbenv or rbenv-vars in production at all.

**Comment by sdarwin** [comment]
> How is Passenger configured?
Nginx compiled with passenger.  

> Are you saying that works locally, but not in production?
It works from command-line scripts in production, but not in the web server.

>  Then you don't need rbenv or rbenv-vars
Well, rbenv is really a good way to manage and switch between multiple rubies. 
It appears to be the case that rbenv is still ok with this configuration, but rbenv-vars would perhaps need some other configuration changes.  Or, it just can't be made to work at all with this setup, because it has no opportunity to load the variables?

Thanks for your feedback. It is an interesting case. I will close the ticket, but if there is anything more we can continue to discuss.

**Comment by michaelmagistro** [comment]
@sdarwin I have been working what I believe to be the exact same issue.

I [posted](http://stackoverflow.com/questions/36126293/activerecord-attempting-to-connect-to-the-wrong-database-using-rbenv) this on SO as well.

Development worked fine. Even `rails console production` on the server worked with `app.get '/'` with no database errors. However, when putting the request through the browser, all hell broke loose.

The problem is that the instructions that Phusion Passenger gives at the end of its installation are not exactly compatible with rbenv-vars.

At the end of the Passenger installation, you are instructed to add the following to `nginx.conf`:

    passenger_root /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/passenger-5.0.26;
    passenger_ruby /home/user/.rbenv/versions/2.3.0/bin/ruby;

However, then as @mislav [pointed out](https://github.com/rbenv/rbenv-vars/issues/27), the Ruby scripts would be spinning up the ruby processes directly instead of through rbenv.

To fix this, what needs to be in `nginx.conf` instead is:

    passenger_root /home/user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/passenger-5.0.26;
    passenger_ruby /home/user/.rbenv/shims/ruby;

**Comment by backwardm** [comment]
@michaelmagistro Thanks for your note! I just now ran into that installing Passenger 5.1.5 in an rbenv setup. My rbenv-vars weren't being read as you noted, but your note to fix the PassengerRuby path helped me fix it.

In my case, I am setting that in the /etc/apache2/sites-available/site file as:

```PassengerRuby /home/deploy/.rbenv/shims/ruby```
